<?php

namespace EntityBundle\Repository;

/**
 * exerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class exerciceRepository extends \Doctrine\ORM\EntityRepository
{
}
