<?php

namespace EntityBundle\Repository;

/**
 * WorkOutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkOutRepository extends \Doctrine\ORM\EntityRepository
{
}
